# Site settings
title: "FreeFanRadio.ca"
description: "The Canadian hub for legal sports radio streams and podcasts."
url: "https://freefanradio.ca"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  stations:
    output: true
    permalink: /:collection/:name/

# Navigation
navigation:
  - title: Home
    url: /
  - title: Stations
    url: /sports/
  - title: Hockey
    url: /hockey/
  - title: Football
    url: /football/
  - title: About
    url: /about/
  - title: Terms
    url: /terms/

# Google AdSense
google_adsense_id: "ca-pub-6728538010774960"  # Your Google AdSense ID

# Social Media
social:
  twitter: freefanradio
  facebook: freefanradio

# SEO
google_analytics: G-NRZ1504M1K  # Your Google Analytics ID
